In [1]:
print("Hello World")

Hello World

In [2]:
import pandas as pd

data = pd.read_csv("intern_performance_dataset.csv")
data.head()

,Intern_ID,Tasks_Assigned,Tasks_Completed,Avg_Task_Time_Hours,Attendance_Percentage,Consistency_Score,Engagement_Score,Feedback_Score,Learning_Progress,Deadline_Misses,Performance_Label
0,INT_0001,11,24,1.70,71.41,5.34,7.47,1.60,1.88,9,High
1,INT_0002,24,23,2.70,85.88,2.76,8.76,1.17,1.40,8,High
2,INT_0003,19,13,6.06,84.62,6.50,2.61,8.44,2.67,6,High
3,INT_0004,15,7,6.99,99.56,3.53,8.20,5.72,5.87,1,High
4,INT_0005,12,6,6.81,56.42,2.86,5.97,7.98,6.81,8,High

In [4]:
data = pd.read_csv("intern_performance_dataset.csv")

In [5]:
data.head()

,Intern_ID,Tasks_Assigned,Tasks_Completed,Avg_Task_Time_Hours,Attendance_Percentage,Consistency_Score,Engagement_Score,Feedback_Score,Learning_Progress,Deadline_Misses,Performance_Label
0,INT_0001,11,24,1.70,71.41,5.34,7.47,1.60,1.88,9,High
1,INT_0002,24,23,2.70,85.88,2.76,8.76,1.17,1.40,8,High
2,INT_0003,19,13,6.06,84.62,6.50,2.61,8.44,2.67,6,High
3,INT_0004,15,7,6.99,99.56,3.53,8.20,5.72,5.87,1,High
4,INT_0005,12,6,6.81,56.42,2.86,5.97,7.98,6.81,8,High

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Intern_ID              700 non-null    object
 1   Tasks_Assigned         700 non-null    int64
 2   Tasks_Completed        700 non-null    int64
 3   Avg_Task_Time_Hours    700 non-null    float64
 4   Attendance_Percentage  700 non-null    float64
 5   Consistency_Score      700 non-null    float64
 6   Engagement_Score       700 non-null    float64
 7   Feedback_Score         700 non-null    float64
 8   Learning_Progress      700 non-null    float64
 9   Deadline_Misses        700 non-null    int64
 10  Performance_Label      700 non-null    object
dtypes: float64(6), int64(3), object(2)
memory usage: 60.3+ KB

In [7]:
data.isnull().sum()

Intern_ID                0
Tasks_Assigned           0
Tasks_Completed          0
Avg_Task_Time_Hours      0
Attendance_Percentage    0
Consistency_Score        0
Engagement_Score         0
Feedback_Score           0
Learning_Progress        0
Deadline_Misses          0
Performance_Label        0
dtype: int64

In [8]:
data.describe()

,Tasks_Assigned,Tasks_Completed,Avg_Task_Time_Hours,Attendance_Percentage,Consistency_Score,Engagement_Score,Feedback_Score,Learning_Progress,Deadline_Misses
count,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000
mean,16.842857,15.902857,4.541329,75.213100,5.481957,5.413129,5.418457,5.458643,4.530000
std,7.455036,7.987418,2.047853,14.447265,2.626661,2.556185,2.579276,2.587474,2.833574
min,5.000000,3.000000,1.030000,50.160000,1.000000,1.010000,1.000000,1.000000,0.000000
25%,10.000000,8.750000,2.700000,62.595000,3.405000,3.170000,3.260000,3.177500,2.000000
50%,17.000000,16.000000,4.630000,75.820000,5.440000,5.400000,5.435000,5.375000,5.000000
75%,23.000000,23.000000,6.315000,87.817500,7.795000,7.600000,7.562500,7.717500,7.000000
max,29.000000,29.000000,8.000000,99.920000,9.980000,10.000000,9.980000,9.970000,9.000000

In [9]:
data = data.drop(columns=["Intern_ID"])

In [11]:
data.columns

Index(['Tasks_Assigned', 'Tasks_Completed', 'Avg_Task_Time_Hours',
       'Attendance_Percentage', 'Consistency_Score', 'Engagement_Score',
       'Feedback_Score', 'Learning_Progress', 'Deadline_Misses',
       'Performance_Label'],
      dtype='object')

In [13]:
data.columns.tolist()

['Tasks_Assigned',
 'Tasks_Completed',
 'Avg_Task_Time_Hours',
 'Attendance_Percentage',
 'Consistency_Score',
 'Engagement_Score',
 'Feedback_Score',
 'Learning_Progress',
 'Deadline_Misses',
 'Performance_Label']

In [15]:
print(data.columns)

Index(['Tasks_Assigned', 'Tasks_Completed', 'Avg_Task_Time_Hours',
       'Attendance_Percentage', 'Consistency_Score', 'Engagement_Score',
       'Feedback_Score', 'Learning_Progress', 'Deadline_Misses',
       'Performance_Label'],
      dtype='object')

In [17]:
list(data.columns)

['Tasks_Assigned',
 'Tasks_Completed',
 'Avg_Task_Time_Hours',
 'Attendance_Percentage',
 'Consistency_Score',
 'Engagement_Score',
 'Feedback_Score',
 'Learning_Progress',
 'Deadline_Misses',
 'Performance_Label']

In [20]:
print(data.columns.tolist())

['Tasks_Assigned', 'Tasks_Completed', 'Avg_Task_Time_Hours', 'Attendance_Percentage', 'Consistency_Score', 'Engagement_Score', 'Feedback_Score', 'Learning_Progress', 'Deadline_Misses', 'Performance_Label']

In [26]:
target_column = "Performance_Label"

X = data.drop(columns=[target_column])
y = data[target_column]

X.head(), y.head()

(   Tasks_Assigned  Tasks_Completed  Avg_Task_Time_Hours  \
 0              11               24                 1.70
 1              24               23                 2.70
 2              19               13                 6.06
 3              15                7                 6.99
 4              12                6                 6.81

    Attendance_Percentage  Consistency_Score  Engagement_Score  Feedback_Score  \
 0                  71.41               5.34              7.47            1.60
 1                  85.88               2.76              8.76            1.17
 2                  84.62               6.50              2.61            8.44
 3                  99.56               3.53              8.20            5.72
 4                  56.42               2.86              5.97            7.98

    Learning_Progress  Deadline_Misses
 0               1.88                9
 1               1.40                8
 2               2.67                6
 3               5.87                1
 4               6.81                8  ,
 0    High
 1    High
 2    High
 3    High
 4    High
 Name: Performance_Label, dtype: object)

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [29]:
# Model 1: Logistic Regression
log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train, y_train)

# Model 2: Decision Tree
tree_model = DecisionTreeClassifier()
tree_model.fit(X_train, y_train)

DecisionTreeClassifier()

In [30]:
y_pred_log = log_model.predict(X_test)
y_pred_tree = tree_model.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score

log_acc = accuracy_score(y_test, y_pred_log)
tree_acc = accuracy_score(y_test, y_pred_tree)

print("Logistic Regression Accuracy:", log_acc)
print("Decision Tree Accuracy:", tree_acc)

Logistic Regression Accuracy: 0.9785714285714285
Decision Tree Accuracy: 0.9785714285714285